import '@/styles/globals.css';

import { type Metadata } from 'next';
import { Geist } from 'next/font/google';

import { TRPCReactProvider } from '@/trpc/react';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '../components/app-sidebar';
import { navigation } from '@/lib/data/navigation';
import { SidebarBreadCrumbs } from '../components/sidebar-breadcrumbs';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
    title: 'Amnezia Panel',
    description: 'Generated by slowy19',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
    subsets: ['latin'],
    variable: '--font-geist-sans',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${geist.variable}`}>
            <body>
                <TRPCReactProvider>
                    <SidebarProvider>
                        <AppSidebar navigation={navigation} />
                        <SidebarInset>
                            <SidebarBreadCrumbs />
                            <main className="px-4 pb-4">{children}</main>
                            <Toaster position="top-right" expand={true} />
                        </SidebarInset>
                    </SidebarProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
